#!/bin/bash
# Complete Hook Compliance Audit
# Runs all audit tools and generates comprehensive report

set -e

echo "🔍 CLAUDE CODE HOOKS - COMPLIANCE AUDIT"
echo "========================================"
echo ""

# Change to project root
cd "$(dirname "$0")/.."

# Step 1: Compliance audit
echo "Step 1/4: Running compliance scanner..."
python3 scratch/audit_hooks_compliance.py > scratch/compliance_results.txt 2>&1
echo "✓ Results saved to scratch/compliance_results.txt"
echo ""

# Step 2: Documentation mapping
echo "Step 2/4: Mapping hooks to official documentation..."
python3 scratch/hook_docs_mapping.py > scratch/documentation_mapping.txt 2>&1
echo "✓ Results saved to scratch/documentation_mapping.txt"
echo ""

# Step 3: Pattern verification
echo "Step 3/4: Verifying documentation patterns..."
python3 scratch/verify_documentation_examples.py > scratch/pattern_verification.txt 2>&1
echo "✓ Results saved to scratch/pattern_verification.txt"
echo ""

# Step 4: Generate summary
echo "Step 4/4: Generating summary report..."

cat > scratch/AUDIT_RESULTS.md <<'EOF'
# Hook Compliance Audit Results

**Generated:** $(date)
**Location:** /home/jinx/workspace/claude-whitebox/.claude/hooks/

---

## Quick Summary

EOF

# Extract key metrics from compliance results
echo "### Compliance Metrics" >> scratch/AUDIT_RESULTS.md
echo "" >> scratch/AUDIT_RESULTS.md
grep -A 5 "COMPLIANCE SCORE" scratch/compliance_results.txt >> scratch/AUDIT_RESULTS.md 2>/dev/null || echo "N/A" >> scratch/AUDIT_RESULTS.md
echo "" >> scratch/AUDIT_RESULTS.md

# Extract pattern coverage
echo "### Documentation Pattern Coverage" >> scratch/AUDIT_RESULTS.md
echo "" >> scratch/AUDIT_RESULTS.md
grep -A 3 "Pattern Coverage" scratch/pattern_verification.txt >> scratch/AUDIT_RESULTS.md 2>/dev/null || echo "N/A" >> scratch/AUDIT_RESULTS.md
echo "" >> scratch/AUDIT_RESULTS.md

# Extract event coverage
echo "### Event Coverage" >> scratch/AUDIT_RESULTS.md
echo "" >> scratch/AUDIT_RESULTS.md
grep "Total events covered" scratch/documentation_mapping.txt >> scratch/AUDIT_RESULTS.md 2>/dev/null || echo "N/A" >> scratch/AUDIT_RESULTS.md
echo "" >> scratch/AUDIT_RESULTS.md

# Add links to detailed reports
cat >> scratch/AUDIT_RESULTS.md <<'EOF'
---

## Detailed Reports

1. **Compliance Scanner Results**
   - File: `scratch/compliance_results.txt`
   - Contains: Issue counts, severity levels, compliant patterns

2. **Documentation Mapping**
   - File: `scratch/documentation_mapping.txt`
   - Contains: Event coverage, hook-to-docs mapping

3. **Pattern Verification**
   - File: `scratch/pattern_verification.txt`
   - Contains: Official pattern usage, anti-patterns detected

4. **Full Compliance Report**
   - File: `scratch/hook_compliance_report.md`
   - Contains: Detailed analysis, recommendations, fix instructions

5. **Summary**
   - File: `scratch/COMPLIANCE_SUMMARY.md`
   - Contains: Executive summary, action plan, testing guide

6. **Audit Complete**
   - File: `scratch/AUDIT_COMPLETE.md`
   - Contains: Final summary, next steps, metadata

---

## How to Fix Issues

### Option 1: Automated Fix (Recommended)
```bash
python3 scratch/apply_all_fixes.py
```

### Option 2: Manual Review
```bash
cat scratch/hook_compliance_report.md
```

---

## Next Steps

1. Review this report
2. Review `scratch/COMPLIANCE_SUMMARY.md` for action plan
3. Run `python3 scratch/apply_all_fixes.py` to fix issues
4. Verify with `python3 scratch/audit_hooks_compliance.py`
5. Test hooks in Claude Code session
6. Commit changes

---

**Audit Status:** ✓ COMPLETE
**Generated by:** Claude Code Compliance Audit Suite
EOF

echo "✓ Summary report saved to scratch/AUDIT_RESULTS.md"
echo ""

# Display summary
echo "========================================"
echo "AUDIT COMPLETE"
echo "========================================"
echo ""
echo "Generated Files:"
echo "  - scratch/compliance_results.txt"
echo "  - scratch/documentation_mapping.txt"
echo "  - scratch/pattern_verification.txt"
echo "  - scratch/AUDIT_RESULTS.md"
echo ""
echo "Detailed Reports (already exist):"
echo "  - scratch/hook_compliance_report.md"
echo "  - scratch/COMPLIANCE_SUMMARY.md"
echo "  - scratch/AUDIT_COMPLETE.md"
echo ""
echo "Quick View:"
echo "  cat scratch/AUDIT_RESULTS.md"
echo ""
echo "Apply Fixes:"
echo "  python3 scratch/apply_all_fixes.py"
echo ""
echo "✓ Audit complete. Review scratch/AUDIT_RESULTS.md for summary."
